apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: postgres
  name: postgres
  namespace: burp
spec:
  containers:
  - image: postgres:14
    name: postgres
    ports:
    - containerPort: 5432
    resources: {}
    volumeMounts:
    - name: postgres-vol
      mountPath: /var/lib/postgresql/data
    envFrom:
    - secretRef:
        name: postgres-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: postgres-vol
      persistentVolumeClaim:
        claimName: postgres-pvc
status: {}
